### PR TITLE
Doc addition and package name fix.

### PR DESCRIPTION
**Pull request by Langriklol**
SecurityCodeScan must be named without `VS2017` as it gives `Package 'SecurityCodeScanVS2017' is incompatible with 'all' frameworks in project`

### CODE REVIEW

**Comment by JarLob** [comment]
Could you elaborate more on your case? SecurityCodeScan2017 is recommended because it is built with .NET core so, I believe, is more suitable for `dotnet.exe` commands. The drawback is it doesn't support VS2015 projects.
You see, one day SCS branch (current master) will be dropped in favor of SCS2017 (maybe it will be when SCS2019 is introduced if newer Roslyn API will be needed). So I would like to know if anything is wrong with SCS2017.

**Comment by Langriklol** [comment]
@JarLob I have to integrate SCS into one of projects built on C# (ASP.NET Core) and I am suppose d to do it with docker (as every job in pipeline is on docker). So after long time reading your documentation and trying to get it I was finally able to manage run the SCS docker scanning the project I needed. The problem occured, when I added the `SecurityCodeScanVS2017` into the packages as it threw `'SecurityCodeScanVS2017' is incompatible with 'all' frameworks in project` but after seeing some folks posts on StackOverflow (I guess or it was some blog, not sure) I saw that they are adding it without the `VS2017` so I tried it too and it works pretty much ok.

**Comment by JarLob** [comment]
1. What is the version of Visual Studio of your projects?
2. What .NET framework version do they target? Is it .NET Core 3.x?
3. Do you have the link to the stackoverflow discussion? The last time I tried it with docker it was exactly opposite - https://gitlab.com/gitlab-org/gitlab/-/issues/4824. Notice that it fails (as expected) to add SCS to a VS2017 project with an error "incompatible with 'all' frameworks"...
4. Could you try running `dotnet nuget locals all -c` as suggested in https://github.com/NuGet/Home/issues/5127#issuecomment-360645795 and try it again with SCS2017?

**Comment by Langriklol** [comment]
@JarLob 
1. No idea, I am not one of developers
2. We are currently targeting 2.2 (and I run it with SCS docker img
3. Y I checked it
4. No change at all

**Comment by JarLob** [comment]
Ok, I thought it might be related to someone recently complaining it doesn't work for him with .NET Core 3.0.
Please, take a look at my changes and let me know if you are ok with that. I can add it as known issue with possible workarounds, but one day SCS2017 will be the main branch and the suggestion to use SCS will be gone...

P.S. Thanks for taking your time to let me know there is the issue!

**Comment by Langriklol** [comment]
@JarLob yup, that seems perfect to me :) (sorry for late response)

**Comment by JarLob** [comment]
BTW, just noticed the package name was wrong it must be `SecurityCodeScan.VS2017`. I get these two errors:
```
error: Unable to find package SecurityCodeScanVS2017. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
error: Package 'SecurityCodeScanVS2017' is incompatible with 'all' frameworks in project 'ConsoleApp1\ConsoleApp1.csproj'.
```

**Comment by Langriklol** [comment]
@JarLob I have tried it too, no worries but without success

**Pull request merged**
