### PR TITLE
 Added warnings about path traversal to audit

### PR DESCRIPTION
**Pull request by zaichenko**
Hello!
I added to audit several sinks from classes FileInfo and Assembly about path traversal.

### CODE REVIEW

**Comment by zaichenko** [comment]
Could someone explain, why so much commits have added to pull request?

**Comment by JarLob** [comment]
> Could anyone explain, please, why so much commits have added to pull request?

Disclaimer: I don't have much experience with Git.

I think it is because every merge you do locally is a new commit to the original repository.
It is better to branch and do your feature on the branch instead of master. For keeping your master in sync with the original master follow https://gist.github.com/CristinaSolana/1885435 (would be interesting to try pulling from master to the branch directly).
Then if you want the latest changes in your branch probably it is better to rebase, than branch.

**Comment by JarLob** [comment]
I'll try creating a new pull request on your behalf.

**Comment by JarLob** [comment]
Does it #98 look good?
P.S. A tip: function parameters are needed only if overloads are very different and a different sink index needs to be specified. Otherwise SCS is smart enough to accept only file name and index.

**Comment by zaichenko** [comment]
> Does #98 look good?
Excellent!

**Pull request closed without merging**
