### PR TITLE
nHibernate SQL Injection

### PR DESCRIPTION
**Pull request by indy-singh**

### CODE REVIEW

**Comment by indy-singh** [comment]
Not entirely sure why the test is failing. Would appreciate any pointers.

**Comment by indy-singh** [comment]
Ah, not used to the VS Test Runner. I can see it can't find the namespaces.

**Comment by indy-singh** [comment]
Getting this error during the test execution:-

```csharp
Diagnostics:
// warning CS1701: Assuming assembly reference 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' used by 'NHibernate' matches identity 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' of 'mscorlib', you may need to supply runtime policy
// Test0.cs(10,13): warning CS1701: Assuming assembly reference 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' used by 'NHibernate' matches identity 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' of 'mscorlib', you may need to supply runtime policy     
```

Pretty much out of ideas.

**Comment by JarLob** [comment]
Yeah, that one was tricky. Looks like NHibernate 4.0 is built with .NET 2.0 and it gave a conflict. Since it is only a warning, I have added a workaround to ignore it.

**Comment by indy-singh** [comment]
Ah! Thanks for that. I was a bit confused.

I'm planning on doing seperate PRs for Cassandra and Npgsql unless you want
me to squash everything under this PR

Indy

**Comment by indy-singh** [comment]
>  Looks like NHibernate 4.0 is built with .NET 2.0 and it gave a conflict.

I tried to pick the latest version with the fewest dependencies. Happy to upgrade to the latest version if you don't mind half of .NET standard coming in too.

**Comment by JarLob** [comment]
> I tried to pick the latest version with the fewest dependencies. Happy to upgrade to the latest version if you don't mind half of .NET standard coming in too.

:) Let's stick to 4.1. At some point the single test project must be split into multiple ones: one .net full, the other .net standard 1.0, yet another .net standard 2.0. But not yet, too lazy for that.

> I'm planning on doing seperate PRs for Cassandra and Npgsql unless you want
me to squash everything under this PR

It's OK to have it under the same PR.

> I'm not sure about using `SCS0035` - is it best to create new error codes and attach them to the respective ones correctly?

Historically there are multiple codes for SQLi in different frameworks, although in general I try to reuse the codes. Keep in mind that every code must have an entry under https://security-code-scan.github.io/#Rules Each number has an example of vulnerable and safe programming code. If you find some SCS code with the safe example under https://security-code-scan.github.io/#SQLInjection that is applicable to your framework it would be less work to reuse the code. Otherwise you need to create a new rule documentation under https://github.com/security-code-scan/security-code-scan/tree/master/website/rules

**Comment by indy-singh** [comment]
> Historically there are multiple codes for SQLi in different frameworks, although in general I try to reuse the codes. Keep in mind that every code must have an entry under https://security-code-scan.github.io/#Rules Each number has an example of vulnerable and safe programming code. If you find some SCS code with the safe example under https://security-code-scan.github.io/#SQLInjection that is applicable to your framework it would be less work to reuse the code. Otherwise you need to create a new rule documentation under https://github.com/security-code-scan/security-code-scan/tree/master/website/rules

I'm happy to do the leg work for the custom codes and error messages. The resolutions for Nhibernate, Cassandra, and Npgsql all differ enough to warrant their own SCS codes. I will do a PR for the website too (hopefully today).

Indy

**Comment by indy-singh** [comment]
I think I'm done. Let me know if any changes are required.

**Comment by JarLob** [comment]
Again, sorry for the delay and thanks for the PR!

**Comment by indy-singh** [comment]
Awesome thanks! Any idea when this will be published to nuget?

**Comment by JarLob** [comment]
I'll try doing it tomorrow. The process is manual.

**Comment by indy-singh** [comment]
Released in https://github.com/security-code-scan/security-code-scan/releases/tag/3.5.0

**Pull request merged**
